apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: donsolly/my_flask_app:v${{ github.run_number }}
        ports:
        - containerPort: 5010
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app
spec:
  ports:
    - port: 5010
      targetPort: 5010
      protocol: TCP
  selector:
    app: my-flask-app
  type: LoadBalancer
